# Generated by Django 2.2.12 on 2020-05-27 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacient', '0005_auto_20200527_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='user_pacient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pacient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
    ]
