# Generated by Django 2.2.12 on 2020-06-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0008_auto_20200601_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresaPacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.Adresa')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.Pacient')),
            ],
        ),
    ]
