# Generated by Django 2.2.12 on 2020-06-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0009_adresapacient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdresaPacient',
        ),
    ]
