# Generated by Django 2.2.12 on 2020-06-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacient', '0006_auto_20200527_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomandariPacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.Pacient')),
                ('recomandari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.Recomandari')),
            ],
        ),
    ]
