# Generated by Django 2.2.12 on 2020-06-01 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fisa_medicala', '0002_datemedicalepacient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datemedicalepacient',
            options={'verbose_name': 'Date Medicale Pacient', 'verbose_name_plural': 'Date Medicale Pacient'},
        ),
        migrations.AlterModelOptions(
            name='recomandaripacient',
            options={'verbose_name': 'Recomandari Pacient', 'verbose_name_plural': 'Recomandari Pacient'},
        ),
        migrations.AddField(
            model_name='datemedicalepacient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='recomandaripacient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
    ]
