# Generated by Django 2.2.12 on 2020-06-01 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacient', '0007_auto_20200601_1017'),
        ('fisa_medicala', '0003_auto_20200601_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvertizarePacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avertizare', models.TextField()),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacient.Pacient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Avertizare Pacient',
                'verbose_name_plural': 'Avertizare Pacient',
            },
        ),
    ]
