# Generated by Django 2.2.12 on 2020-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisa_medicala', '0004_avertizarepacient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avertizarepacient',
            name='avertizare',
            field=models.CharField(max_length=255),
        ),
    ]
